### ISSUE TITLE
problemes in vampire savior and jojo

### ISSUE THREAD

**Issue by StardustX7** [angelkillah/MooHijack#6]
cannot start a game in jojo, vampire savior keeps on rebooting again and again

**Comment by angelkillah** [comment]
which OS are you using, which mode do you use?
Please read the "readme.txt" carefully

**Comment by StardustX7** [comment]
ok my bad I did not read the extra notes, sorry

**Comment by StardustX7** [comment]
did not read the extra notes, work as it is supposed to work at this point
