### ISSUE TITLE
JoJoBan Dipswitches

### ISSUE THREAD

**Issue by feuras** [angelkillah/MooHijack#7]
Really happy with the implementation of jojoban, thanks dude!

Several characters are missing however - the game has an obtuse secret code in order to enable them. 

"Open the debug menu select the seventh option, then on the next screen select the second option. On this screen, input [Up, Down, Right, Left, Light (A), Medium (B), Hard (C), Stand]. You will hear Dio "WRYYYYYYY!". Save the settings and the ROM will reset. Now you'll have all characters unlocked"

If you you can update the multi.save to have this pre-enabled that would be sweet. Cheers, looking forward to Warzard!

**Comment by angelkillah** [comment]
fix ! It will be integrated in the next patch.

Meanwhile you can download the new savestate here :
https://drive.google.com/file/d/1uflWUqulRQripVJnAmOMUA8mOZ10xBqS/view?usp=sharing

Just replace the file db\jojoban\multi.sav with this new one (obviously the other player should do the same)

**Comment by feuras** [comment]
Thank you. Access is denied on the Google Drive file.

**Comment by angelkillah** [comment]
try again, it should works now
