### ISSUE TITLE
Border assets for Jojos

### ISSUE THREAD

**Issue by feuras** [angelkillah/MooHijack#8]
Hey, I made some border assets for Jojos - not sure how you're loading assets into the game, but if it works that'd be cool.

https://drive.google.com/open?id=11_5rsuvSWwJi-8XuTAidayLtOprtYRm8

**Comment by angelkillah** [comment]
![Capture](https://user-images.githubusercontent.com/1363337/82806156-80628280-9e85-11ea-8c61-0db31d699c4e.PNG)

It will look like this.
Is this ok?

Thanks for your contribution (:
If these borders look good for you, i'll commit the changes

**Comment by angelkillah** [comment]
custom border supports added with the following commit 
https://github.com/angelkillah/MooHijack/commit/ab99e16a833c1fadeeaa8555530e570ecc7f8b9e

**Comment by feuras** [comment]
Few small changes, updated version here - https://drive.google.com/open?id=1H25H6XkXlEeIRNFY3NWE3uJkOao3S1aL 

WIll take a look at Darkstalkers later - cheers!
